// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20210109172526_addedTwoPersons")]
    partial class addedTwoPersons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAL.Entities.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("HasGender")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPhoneType")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPosition")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dictionaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasGender = false,
                            HasPhoneType = false,
                            HasPosition = true,
                            Title = "manager"
                        },
                        new
                        {
                            Id = 2,
                            HasGender = false,
                            HasPhoneType = false,
                            HasPosition = true,
                            Title = "CEO"
                        },
                        new
                        {
                            Id = 3,
                            HasGender = false,
                            HasPhoneType = false,
                            HasPosition = true,
                            Title = "shveicar"
                        },
                        new
                        {
                            Id = 4,
                            HasGender = true,
                            HasPhoneType = false,
                            HasPosition = false,
                            Title = "Male"
                        },
                        new
                        {
                            Id = 5,
                            HasGender = true,
                            HasPhoneType = false,
                            HasPosition = false,
                            Title = "Female"
                        },
                        new
                        {
                            Id = 6,
                            HasGender = false,
                            HasPhoneType = true,
                            HasPosition = false,
                            Title = "mobile"
                        },
                        new
                        {
                            Id = 7,
                            HasGender = false,
                            HasPhoneType = true,
                            HasPosition = false,
                            Title = "work"
                        },
                        new
                        {
                            Id = 8,
                            HasGender = false,
                            HasPhoneType = true,
                            HasPosition = false,
                            Title = "Home"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("PositionId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "name1",
                            GenderId = 5,
                            LastName = "LastName1",
                            Mail = "test@mail.com",
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "name2",
                            GenderId = 5,
                            LastName = "LastName2",
                            Mail = "test@mail.com",
                            PositionId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "name3",
                            GenderId = 5,
                            LastName = "LastName3",
                            Mail = "test@mail.com",
                            PositionId = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PnoneTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PnoneTypeId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("DAL.Entities.Person", b =>
                {
                    b.HasOne("DAL.Entities.Dictionary", "Gender")
                        .WithMany("PersonGenders")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Dictionary", "Position")
                        .WithMany("PersonPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DAL.Entities.PhoneNumber", b =>
                {
                    b.HasOne("DAL.Entities.Person", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Dictionary", "PhoneType")
                        .WithMany("PhoneTypes")
                        .HasForeignKey("PnoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("PhoneType");
                });

            modelBuilder.Entity("DAL.Entities.Dictionary", b =>
                {
                    b.Navigation("PersonGenders");

                    b.Navigation("PersonPositions");

                    b.Navigation("PhoneTypes");
                });

            modelBuilder.Entity("DAL.Entities.Person", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
